### ISSUE TITLE
YORIP機能洗い出し

### ISSUE THREAD

**Issue by KanekoCadlab** [kurumu-rika/first-app#19]
![image](https://user-images.githubusercontent.com/100031087/161381555-b5bdbbc8-3b3c-429b-9bc1-1a07e92f8adf.png)
![image](https://user-images.githubusercontent.com/100031087/161381586-9791e5fd-def0-428f-80d1-4ef3104821f2.png)
![image](https://user-images.githubusercontent.com/100031087/161381606-be6e88ff-6a11-4310-acd0-cefab6d5a42b.png)
![image](https://user-images.githubusercontent.com/100031087/161381615-9b09273b-3c85-4b8b-a925-4379a6e29660.png)
![image](https://user-images.githubusercontent.com/100031087/161381646-ad9c5332-1598-416e-af51-e30b99b15104.png)

**Comment by hirano0709** [comment]
兼子くんに共有してもらったので，クローズ．
